# Generated by Django 2.2.5 on 2019-09-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=25)),
                ('background', models.ImageField(upload_to='media/')),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(blank=True, max_length=100, null=True)),
                ('copyright', models.CharField(max_length=50)),
            ],
        ),
    ]
