# Generated by Django 2.2.5 on 2019-09-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='more',
            field=models.TextField(blank=True, null=True),
        ),
    ]
