# Generated by Django 2.2.5 on 2019-09-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0007_post_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='add_list',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
