# Generated by Django 2.2.5 on 2019-09-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0009_auto_20190907_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
