# Generated by Django 2.2.5 on 2019-09-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0010_auto_20190907_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addlist',
            name='add_list',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
