# Generated by Django 2.2.5 on 2019-09-07 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0011_auto_20190907_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addlist',
            name='list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todo_app.Post'),
        ),
    ]
