# Generated by Django 2.2.5 on 2019-09-11 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0013_verification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addlist',
            name='add_list',
        ),
    ]
