# Generated by Django 2.2.5 on 2019-09-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0014_remove_addlist_add_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='addlist',
            name='add_list',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
