# Generated by Django 2.2.5 on 2019-09-12 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0017_auto_20190911_1415'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddList',
        ),
    ]
