# Generated by Django 2.2.5 on 2019-09-12 12:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0018_delete_addlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='shared_user',
            field=models.ManyToManyField(related_name='shared_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
