# Generated by Django 2.2.5 on 2019-09-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0023_commentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='more',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
