# Generated by Django 2.2.5 on 2019-09-13 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0024_auto_20190913_0540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='post',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
